on:
    push:
        tags: ['*']
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - id: get_tag
              run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
            - env:
                  RELEASE_VERSION: ${{ steps.get_tag.outputs.tag }}
              run: |
                  echo $RELEASE_VERSION
