on:
    push:
        tags: '*'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v3
              with:
                  script: |
                      echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
